In [4]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr
print(arr.shape)

(2, 2, 3)


In [9]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1[0:7:2])

[1 3 5 7]


In [14]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1[-5:-1])

[4 5 6 7]


In [16]:
import numpy as np
arr2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr2.reshape(4,3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
import numpy as np
arr4=np.array([1,2,3])
arr5=np.array([4,5,6])
arr6=np.concatenate((arr4,arr5))
print(arr6)

[1 2 3 4 5 6]


In [22]:
import numpy as np
arr7=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=np.array_split(arr7,4)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [28]:
import numpy as np
arr8=np.array([1,2,3,4,4,5,6,7,4,4,8,9,10,11,4,4,12])
x=np.where(arr8==4)
print(x)

(array([ 3,  4,  8,  9, 14, 15]),)


In [29]:
import numpy as np
arr9=np.array([3,2,1,4,6,5,7,9,8])
print(np.sort(arr9))

[1 2 3 4 5 6 7 8 9]


In [30]:
arr10=np.array([1,2,3,4])
x=[True,True,False,False]
newarr=arr10[x]
print(newarr)

[1 2]


In [32]:
from numpy import random
y=random.randint(100,size=(3,4))
print(y)

[[12 48 79 75]
 [ 8 18 48 91]
 [71 16 53 87]]


In [34]:
from numpy import random
y=random.rand(4)
print(y)

[0.40157249 0.02947284 0.36721217 0.00310688]


In [35]:
A=np.array([1,2,3])
B=np.array([2,3,4])
print(np.dot(A,B))

20
